import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { formatImproveReport, runImprove } from "../src/improve.js";

const privacySentinels = [
  "BB_CC_LITE_RAW_PROMPT_SENTINEL",
  "BB_CC_LITE_TOOL_OUTPUT_SENTINEL",
  "BB_CC_LITE_API_KEY_SENTINEL",
  "BB_CC_LITE_FILE_CONTENT_SENTINEL",
  "BB_CC_LITE_RAW_COMMAND_SENTINEL",
  "BB_CC_LITE_RAW_SESSION_SENTINEL",
  "mcp__privateServer__rawPrivacyTool",
  "/tmp/bb-cc-lite/private/workspace/src/secret.ts",
  "secret.ts"
];

describe("improve", () => {
  it("is review-only by default and keeps project suggestions out of files", async () => {
    const tempDir = await mkdtemp(join(tmpdir(), "bb-cc-lite-improve-review-"));
    try {
      const homeDir = join(tempDir, "home");
      const projectDir = join(tempDir, "project");
      await writeProjectTranscript(homeDir, projectDir, "one.jsonl", uncheckedEditTranscript("one"));
      await writeProjectTranscript(homeDir, projectDir, "two.jsonl", uncheckedEditTranscript("two"));

      const report = await runImprove({ homeDir, projectDir });
      const formatted = formatImproveReport(report);

      expect(report).toMatchObject({
        kind: "improve",
        mode: "review",
        suggestions: [
          expect.objectContaining({
            scope: "project",
            target: "project_claude",
            writable: true,
            lessonKey: "unchecked_edits"
          })
        ],
        applied: []
      });
      await expect(pathExists(join(projectDir, "CLAUDE.md"))).resolves.toBe(false);
      expect(formatted).toContain("review only");
      expect(formatted).toContain("After changing code, run the smallest relevant check.");
      expectNoPrivacySentinels(report, formatted);
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it("applies project suggestions only inside the marked CLAUDE.md block and creates a backup", async () => {
    const tempDir = await mkdtemp(join(tmpdir(), "bb-cc-lite-improve-apply-"));
    try {
      const homeDir = join(tempDir, "home");
      const projectDir = join(tempDir, "project");
      const claudePath = join(projectDir, "CLAUDE.md");
      const agentsPath = join(projectDir, "AGENTS.md");
      await mkdir(projectDir, { recursive: true });
      await writeFile(claudePath, "# Project instructions\n\nKeep this user-authored line.\n", "utf8");
      await writeFile(agentsPath, "Do not edit this file.\n", "utf8");
      await writeProjectTranscript(homeDir, projectDir, "one.jsonl", uncheckedEditTranscript("one"));
      await writeProjectTranscript(homeDir, projectDir, "two.jsonl", uncheckedEditTranscript("two"));

      const report = await runImprove({ homeDir, projectDir, apply: true, now: new Date("2026-06-05T10:00:00.000Z") });
      const formatted = formatImproveReport(report);
      const claudeText = await readFile(claudePath, "utf8");
      const backupNames = (await readdir(projectDir)).filter((name) => name.startsWith("CLAUDE.md.bb-cc-lite-backup-"));
      const backupText = await readFile(join(projectDir, backupNames[0] || ""), "utf8");

      expect(report.applied).toEqual([
        expect.objectContaining({
          target: "project_claude",
          changed: true,
          backupCreated: true,
          blockAction: "created"
        })
      ]);
      expect(claudeText).toContain("Keep this user-authored line.");
      expect(claudeText).toContain("<!-- bb-cc-lite improve:start -->");
      expect(claudeText).toContain("- After changing code, run the smallest relevant check.");
      expect(claudeText).toContain("<!-- bb-cc-lite improve:end -->");
      expect(backupText).toBe("# Project instructions\n\nKeep this user-authored line.\n");
      await expect(readFile(agentsPath, "utf8")).resolves.toBe("Do not edit this file.\n");
      expect(formatted).toContain("project CLAUDE.md: created; backup created");
      expectNoPrivacySentinels(report, formatted, claudeText, backupText);
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it("updates an existing marked CLAUDE.md block without rewriting unrelated content", async () => {
    const tempDir = await mkdtemp(join(tmpdir(), "bb-cc-lite-improve-update-"));
    try {
      const homeDir = join(tempDir, "home");
      const projectDir = join(tempDir, "project");
      const claudePath = join(projectDir, "CLAUDE.md");
      await mkdir(projectDir, { recursive: true });
      await writeFile(
        claudePath,
        [
          "# Project instructions",
          "",
          "Keep this line before.",
          "",
          "<!-- bb-cc-lite improve:start -->",
          "## bb-cc-lite lessons",
          "- Old generated lesson.",
          "<!-- bb-cc-lite improve:end -->",
          "",
          "Keep this line after.",
          ""
        ].join("\n"),
        "utf8"
      );
      await writeProjectTranscript(homeDir, projectDir, "one.jsonl", blindRetryTranscript("one"));
      await writeProjectTranscript(homeDir, projectDir, "two.jsonl", blindRetryTranscript("two"));

      const report = await runImprove({ homeDir, projectDir, apply: true, now: new Date("2026-06-05T11:00:00.000Z") });
      const claudeText = await readFile(claudePath, "utf8");

      expect(report.applied).toEqual([
        expect.objectContaining({
          target: "project_claude",
          changed: true,
          backupCreated: true,
          blockAction: "updated"
        })
      ]);
      expect(claudeText).toContain("Keep this line before.");
      expect(claudeText).toContain("Keep this line after.");
      expect(claudeText).not.toContain("Old generated lesson.");
      expect(claudeText).toContain(
        "- Do not rerun a failed validation check until you inspect the first failure and make one targeted change."
      );
      expectNoPrivacySentinels(report, claudeText);
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it("classifies repeated all-project behavior as a global suggestion", async () => {
    const tempDir = await mkdtemp(join(tmpdir(), "bb-cc-lite-improve-global-"));
    try {
      const homeDir = join(tempDir, "home");
      await writeTranscript(
        join(homeDir, ".claude", "projects", "private-project-one", "session.jsonl"),
        blindRetryTranscript("one")
      );
      await writeTranscript(
        join(homeDir, ".claude", "projects", "private-project-two", "session.jsonl"),
        blindRetryTranscript("two")
      );

      const report = await runImprove({ homeDir, allProjects: true, global: true, recent: 10 });
      const formatted = formatImproveReport(report);

      expect(report.suggestions).toContainEqual(
        expect.objectContaining({
          scope: "global",
          target: "global_claude",
          writable: true,
          lessonKey: "blind_validation_retry"
        })
      );
      expect(formatted).toContain("global CLAUDE.md");
      expect(formatted).not.toContain("private-project-one");
      expect(formatted).not.toContain("private-project-two");
      expectNoPrivacySentinels(report, formatted);
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it("keeps one-off transcript lessons session-only", async () => {
    const tempDir = await mkdtemp(join(tmpdir(), "bb-cc-lite-improve-session-"));
    try {
      const transcriptPath = join(tempDir, "single.jsonl");
      await writeTranscript(transcriptPath, uncheckedEditTranscript("single"));

      const report = await runImprove({ transcriptPath });
      const formatted = formatImproveReport(report);

      expect(report.suggestions).toEqual([
        expect.objectContaining({
          scope: "session",
          target: "session_report",
          writable: false,
          lessonKey: "unchecked_edits"
        })
      ]);
      expect(formatted).toContain("session-only; not written to CLAUDE.md");
      expectNoPrivacySentinels(report, formatted);
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });
});

async function writeProjectTranscript(homeDir: string, projectDir: string, fileName: string, lines: string[]): Promise<void> {
  await writeTranscript(join(homeDir, ".claude", "projects", claudeProjectDirectoryName(projectDir), fileName), lines);
}

async function writeTranscript(path: string, lines: string[]): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${lines.join("\n")}\n`, "utf8");
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await readFile(path, "utf8");
    return true;
  } catch {
    return false;
  }
}

function claudeProjectDirectoryName(projectDir: string): string {
  return resolve(projectDir).replaceAll(/[\\/]/gu, "-");
}

function uncheckedEditTranscript(idPrefix: string): string[] {
  return [
    toolUse(`${idPrefix}-edit`, "Edit", {
      file_path: privacySentinels[7],
      old_string: privacySentinels[3],
      new_string: "safe"
    }),
    toolResult(`${idPrefix}-edit`, false)
  ];
}

function blindRetryTranscript(idPrefix: string): string[] {
  return [1, 2, 3].flatMap((index) => [
    toolUse(`${idPrefix}-test-${index}`, "Bash", { command: `npm test -- ${privacySentinels[4]}` }),
    toolResult(`${idPrefix}-test-${index}`, true)
  ]);
}

function toolUse(id: string, name: string, input: Record<string, unknown>): string {
  return JSON.stringify({
    session_id: privacySentinels[5],
    type: "assistant",
    message: {
      role: "assistant",
      content: [{ type: "tool_use", id, name, input }]
    }
  });
}

function toolResult(id: string, isError: boolean): string {
  return JSON.stringify({
    type: "user",
    message: {
      role: "user",
      content: [
        {
          type: "tool_result",
          tool_use_id: id,
          is_error: isError,
          content: `${privacySentinels[1]} ${privacySentinels[2]} ${privacySentinels[3]} ${privacySentinels[7]}`
        }
      ]
    }
  });
}

function expectNoPrivacySentinels(...values: unknown[]): void {
  const serialized = values.map((value) => (typeof value === "string" ? value : JSON.stringify(value))).join("\n");
  for (const sentinel of privacySentinels) {
    expect(serialized).not.toContain(sentinel);
  }
}
